### ISSUE TITLE
WIP【目次案】ユーザインタフェース応用

### ISSUE THREAD

**Issue by yanzm** [TechBooster/AndroidOpenTextbook#16]
基礎で何やるかはっきりしないと何とも。。。

* dp
* レイアウトの種類（LinearLayout、RelativeLayout、、、）
* リソース（リソース識別子、shapeなど含む）
* 構成
* ナビゲーション

**Comment by mhidaka** [comment]
ほうちごめんね。m1をリリース済みのため一旦Closeします。
