### ISSUE TITLE
【目次案】セキュリティ

### ISSUE THREAD

**Issue by ynakanishi** [TechBooster/AndroidOpenTextbook#20]
表現は置いといて、以下のようなことが必要かと思います。

### アンチパターン(証明書検証を無効化する)

開発中の無効化をリリースビルドに残さない方法 (Gradleを活用せよ)

## 外部サービス利用時のセキュリティ
例: OAuth での認可取得は外部ブラウザを使って実施せよ

### ProGuardbility  を意識したコードの書き方
例: xml で onClick 宣言すると辛いことになる

**Comment by mhidaka** [comment]
TechIns版からのバックポートが残ってるけど本件とは関係ないのでこのIssueはCloseします
