### ISSUE TITLE
サンプルコードのパッケージ名は？

### ISSUE THREAD

**Issue by fkmhrk** [TechBooster/AndroidOpenTextbook#57]
org.techbooster
と
jp.techinstitute
のどちらが正しい？

**Comment by mhidaka** [comment]
androidopentextbook.jp があります。
jp.androidopentextbook がおすすめ値です！

**Comment by fkmhrk** [comment]
了解

**Comment by sys1yagi** [comment]
あれ、これってREADME.mdとかにかいておいた方がよくないですか？
