### ISSUE TITLE
ビルドの成果物に箇条書きのテキストが表示されない

### ISSUE THREAD

**Issue by ichigotake** [TechBooster/AndroidOpenTextbook#62]
`grunt pdf`, `grunt html`, 共に同様の症状です(画像はpdfのもの)。

Re:VIEW の利用経験は全くないので、原因がわかりません。どんな解決策があるんでしょうか。

![2015-06-17 10 06 11](https://cloud.githubusercontent.com/assets/381483/8197844/0805efd8-14d9-11e5-80f8-19428c3bb69f.png)
## 環境

READMEの[ビルド方法](https://github.com/TechBooster/AndroidOpenTextbook/blob/89dd54c7ba5969517c78f79b514a1f0c0f690d7b/README.md#ビルド方法)を見ながらビルド環境を用意しました。

```
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D136

$ grunt --version
grunt-cli v0.1.13
grunt v0.4.4

## 数あるRe:VIEWのコマンドから無作為に一つを選択してバージョンを表示
$ review-check --version
review-check 1.5.0

$ tex --version
TeX 3.14159265 (TeX Live 2015)
kpathsea version 6.2.1
(ライセンスは省略)
```

**Comment by mhidaka** [comment]
現象を確認しました。
演習用のコンテンツのため意図的に空行にしてあるようです。
https://github.com/TechBooster/AndroidOpenTextbook/blob/d482631d5f7dd43688143acce5890a5024ce9ac5/articles/uibasic-01.re#L103

注釈：Androidプログラミングの講義のため作成した経緯があり、該当部分は紙媒体が前提

**Comment by mhidaka** [comment]
他、なにかあればreopenしてください :+1:

**Comment by ichigotake** [comment]
なるほど理解しました :+1:
